# Generated by Django 2.0.13 on 2019-03-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificadorCartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cartao', models.CharField(choices=[('cred', 'Cartão de Crédito'), ('deb', 'Cartão de Débito')], max_length=4)),
            ],
        ),
    ]
